import { PlanSummary } from "types/app";

// list of all current plans
export const plans: PlanSummary[] = [
  ["c25k", "Couch to 5K", "5K"],
  ["c25k_rbp", "Couch to 5K -- Runner's Blueprint", "5K"],
  ["frr_5k_01", "Faster Road Racing: 5K Schedule 1", "5K"],
  ["frr_5k_02", "Faster Road Racing: 5K Schedule 2", "5K"],
  ["frr_5k_03", "Faster Road Racing: 5K Schedule 3", "5K"],
  ["frr_8k10k_01", "Faster Road Racing: 8K-10K Schedule 1", "10K"],
  ["frr_8k10k_02", "Faster Road Racing: 8K-10K Schedule 2", "10K"],
  ["frr_8k10k_03", "Faster Road Racing: 8K-10K Schedule 3", "10K"],
  [
    "frr_15k_10m_01",
    "Faster Road Racing: 15k and 10 Miles Schedule 1",
    "15K/10M",
  ],
  [
    "frr_15k_10m_02",
    "Faster Road Racing: 15k and 10 Miles Schedule 2",
    "15K/10M",
  ],
  [
    "frr_15k_10m_03",
    "Faster Road Racing: 15k and 10 Miles Schedule 3",
    "15K/10M",
  ],
  ["frr_bt_01", "Faster Road Racing: Base Training 1", "Base"],
  ["frr_bt_02", "Faster Road Racing: Base Training 2", "Base"],
  ["frr_bt_03", "Faster Road Racing: Base Training 3", "Base"],
  [
    "frr_multiple_distances_01",
    "Faster Road Racing: Multiple Distances 1",
    "Multiple Distances",
  ],
  [
    "frr_multiple_distances_02",
    "Faster Road Racing: Multiple Distances 2",
    "Multiple Distances",
  ],
  [
    "frr_multiple_distances_03",
    "Faster Road Racing: Multiple Distances 3",
    "Multiple Distances",
  ],
  [
    "pfitz_half_12_47",
    "Faster Road Racing: Half Marathon Schedule 1, 31 to 47 miles per Week",
    "Half Marathon",
  ],
  [
    "pfitz_half_12_63",
    "Faster Road Racing: Half Marathon Schedule 2, 46 to 63 miles per Week",
    "Half Marathon",
  ],
  [
    "pfitz_half_12_84",
    "Faster Road Racing: Half Marathon Schedule 3, 61 to 84 miles per Week",
    "Half Marathon",
  ],
  [
    "pfitz_half_12_100",
    "Faster Road Racing: Half Marathon Schedule 4, 81 to 100 miles per Week",
    "Half Marathon",
  ],
  ["hansons_c210k", "Hansons Couch Potato to 10k", "10K"],
  ["hansons_adv_half", "Hansons Advanced Half Marathon", "Half Marathon"],
  ["hansons_beg_half", "Hansons Beginner Half Marathon", "Half Marathon"],
  ["higdon_adv_mara1", "Hal Higdon: Advanced 1", "Marathon"],
  ["higdon_adv_mara2", "Hal Higdon: Advanced 2", "Marathon"],
  ["higdon_int_mara1", "Hal Higdon: Intermediate 1", "Marathon"],
  ["higdon_int_mara2", "Hal Higdon: Intermediate 2", "Marathon"],
  ["higdon_nov_mara1", "Hal Higdon: Novice 1", "Marathon"],
  ["higdon_nov_mara2", "Hal Higdon: Novice 2", "Marathon"],
  ["higdon_mara3", "Hal Higdon: Marathon 3", "Marathon"],
  ["higdon_senior_mara", "Hal Higdon: Senior Marathon", "Marathon"],
  ["higdon_half3", "Hal Higdon: Half Marathon 3", "Half Marathon"],
  [
    "higdon_int_half1",
    "Hal Higdon: Half Marathon Intermediate 1",
    "Half Marathon",
  ],
  [
    "higdon_int_half2",
    "Hal Higdon: Half Marathon Intermediate 2",
    "Half Marathon",
  ],
  ["higdon_nov_half1", "Hal Higdon: Half Marathon Novice 1", "Half Marathon"],
  ["higdon_nov_half2", "Hal Higdon: Half Marathon Novice 2", "Half Marathon"],
  ["hansons_adv_mara", "Hansons Advanced Marathon", "Marathon"],
  ["hansons_beg_mara", "Hansons Beginner Marathon", "Marathon"],
  [
    "coogan_pbr_mara_up_to_65",
    "Personal Best Running: 16-Week Marathon - Up to 65 Miles per Week",
    "Marathon",
  ],
  ["boston_level_one", "Boston Marathon Level 1 Plan", "Marathon"],
  ["boston_level_two", "Boston Marathon Level 2 Plan", "Marathon"],
  ["boston_level_three", "Boston Marathon Level 3 Plan", "Marathon"],
  ["boston_level_four", "Boston Marathon Level 4 Plan", "Marathon"],
  [
    "pfitz_12_55",
    "Pfitzinger/Douglas: Up to 55 miles per week, 12-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_12_70",
    "Pfitzinger/Douglas: 55 to 70 Miles per Week, 12-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_12_85",
    "Pfitzinger/Douglas: 70 to 85 Miles per Week, 12-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_12_more_than_85",
    "Pfitzinger/Douglas: More Than 85 Miles per Week, 12-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_18_55",
    "Pfitzinger/Douglas: Up to 55 miles per week, 18-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_18_70",
    "Pfitzinger/Douglas: 55 to 70 Miles per Week, 18-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_18_85",
    "Pfitzinger/Douglas: 70 to 85 Miles per Week, 18-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_18_more_than_85",
    "Pfitzinger/Douglas: More Than 85 Miles per Week, 18-week schedule (third edition)",
    "Marathon",
  ],
  [
    "pfitz_multi_4",
    "Pfitzinger/Douglas: Multiple Marathons, 4 Weeks Between Marathons",
    "Marathon",
  ],
  [
    "pfitz_55_recovery",
    "Pfitzinger/Douglas: Marathon up to 55 Miles - 5 Week Recovery Block",
    "Marathon",
  ],
];
